name: Release Agni OS ISO

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    permissions:
      contents: write

    container:
      image: archlinux:latest
      options: --privileged
      
    steps:
      - uses: actions/checkout@v3

      - name: Set current date as environment variable
        run: echo "DATE=`date +'%Y.%m.%d'`" >>$GITHUB_ENV
        
      - name: Synchronise package repositories and install archiso
        run: pacman -Syu --noconfirm archiso git archlinux-keyring reflector wget
        
      - name: Running Reflector
        run: |
          reflector --country "France,Sweden" \
          --verbose \
          --sort rate \
          --protocol https \
          --latest 5 \
          --save /etc/pacman.d/mirrorlist
          pacman -Syu
          
      - name: Building Agni OS ISO
        run: |
            pacman -Syu
            wget https://raw.githubusercontent.com/agnios/agni-iso/main/pacman.conf -O /etc/pacman.conf
            mkarchiso -v -w ./work -o ./out ./
            echo "ISO Built in ./out folder!"
            
      - name: Release ISO File
        uses: ncipollo/release-action@v1
        with:
            artifacts: "out/*.iso"
            body: "v2.0.0"
            generateReleaseNotes: false
            name: "Agni OS - v0.5"
            tag: ${{ env.DATE }}
